packages:
   - packages/*

overrides:
   '@calycode/cli': link:../../../../Library/pnpm/global/5/node_modules/@calycode/cli
   '@calycode/core': link:packages/core
   '@calycode/types': link:packages/types
   '@calycode/utils': link:packages/utils
