# .github/workflows/upload-docs.yml
name: Release Docs for Caly-Xano CLI

on:
   workflow_dispatch

jobs:
   release:
      name: Release Docs
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Install pnpm
           uses: pnpm/action-setup@v4
           with:
              run_install: true

         - name: Setup Node
           uses: actions/setup-node@v4
           with:
              node-version: 20.x
              cache: 'pnpm'
              registry-url: 'https://registry.npmjs.org'
              scope: '@calycode'
              always-auth: true
           env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

         - name: Install dependencies
           run: pnpm install --frozen-lockfile

         - name: Update the docs
           run: pnpm build:docs

         # Upload docs to GCP ONLY after publishing
         - name: Upload docs
           uses: './.github/actions/upload-docs'
           with:
              gcp_credentials: '${{ secrets.GCP_CREDENTIALS }}'
